USE LogDB;

CREATE TABLE IF NOT EXISTS SystemLogs (
    log_id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    severity ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'),
    serverName VARCHAR(32) NOT NULL,
    message TEXT
);

CREATE TABLE IF NOT EXISTS SecurityLogs (
    log_id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    eventType VARCHAR(255),
    sourceIp VARCHAR(16),
    userId BINARY(16),
    details TEXT
);